In [35]:
import numpy as np

def dist_to_origin(ar,dim):
    origin=np.zeros(dim)
    return np.linalg.norm(ar-origin)

def draw_sample(dim,std):
    m=np.zeros(dim)
    var=std**2
    cov=var*np.identity(dim)
    return np.random.multivariate_normal(m,cov,dim)

a=np.array([1,4])
a=np.array([[2,0,0],[0,7,0],[0,0,1]])

d=dist_to_origin(a,3)
print(f'Distance to (2,7,11) {d:0.4}')

DIMENSION=3
STD_DEV=1

s=draw_sample(DIMENSION, STD_DEV)
print(f'Random sample from mu=0 var={STD_DEV**2} dim=({DIMENSION},{DIMENSION})')
print(f'{s}')

print(f'Sample point is {dist_to_origin(s,DIMENSION):0.4} from origin')


Distance to (2,7,11) 7.348
Random sample from mu=0 var=1 dim=(3,3)
[[ 1.43723257 -1.22921531  0.85388981]
 [ 1.39069431  0.2577548  -0.06032537]
 [-0.04201311  0.37974636 -1.95770953]]
Sample point is 3.208 from origin
